### ISSUE TITLE
core rest pipeline package causing AzureSpecialProperties test failure 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1187]
Some of the error info is like 
```
  29) AzureSpecialProperties
       headers
         should allow custom-named request-id headers to be used with parameter grouping:
     Error: Bearer token authentication is not permitted for non-TLS protected (non-https) URLs.
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/bearerTokenAuthenticationPolicy.ts:159:15)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/userAgentPolicy.ts:39:14)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/tracingPolicy.ts:54:16)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/formDataPolicy.ts:23:14)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/decompressResponsePolicy.ts:24:14)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-rest-pipeline/src/policies/proxyPolicy.ts:225:14)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at Object.sendRequest (node_modules/@azure/core-client/src/serializationPolicy.ts:60:14)
      at /mnt/vss/_work/1/s/node_modules/@azure/core-rest-pipeline/src/pipeline.ts:162:25
      at HttpPipeline.sendRequest (node_modules/@azure/core-rest-pipeline/src/pipeline.ts:168:12)
      at AzureSpecialPropertiesClient.sendRequest (node_modules/@azure/core-client/src/serviceClient.ts:103:26)
      at AzureSpecialPropertiesClient.sendOperationRequest (node_modules/@azure/core-client/src/serviceClient.ts:185:38)
      at HeaderImpl.customNamedRequestIdParamGrouping (test/integration/generated/azureSpecialProperties/src/operations/header.ts:61:24)
      at /mnt/vss/_work/1/s/test/integration/azureSpecialProperties.spec.ts:348:46
      at Generator.next (<anonymous>)
      at /mnt/vss/_work/1/s/test/integration/azureSpecialProperties.spec.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test/integration/azureSpecialProperties.spec.ts:4:12)
      at Context.it (test/integration/azureSpecialProperties.spec.ts:338:102)
```

currently we have to skip all the test in azureSpecialProperties.spec.ts to by pass this issue. and we need to release a new package for @azure/core-rest-pipeline to address this issue.

**Comment by sarangan12** [comment]
@qiaozha Is this issue still valid? If so, Could you please provide the repro scenarios? Thanks

**Comment by sarangan12** [comment]
Actually, I see https://github.com/Azure/autorest.typescript/blob/main/test/integration/azureSpecialProperties.spec.ts#L18 and this still seems to be valid. Let me work on this and get back to you.
