### ISSUE TITLE
latest autorest core seems to have some problem

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1188]
```
Unexpected error while logging TypeError: sink.log is not a function
    at AutorestAsyncLogger.emitLog (/home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11877:18)
    at AutorestAsyncLogger.logMessageAsync (/home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11891:14)
    at async /home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11935:17
Unexpected error while logging TypeError: sink.log is not a function
    at AutorestAsyncLogger.emitLog (/home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11877:18)
    at AutorestAsyncLogger.logMessageAsync (/home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11891:14)
    at async /home/vsts/.autorest/@autorest_core@3.6.0/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:11935:17
```
I have changed the test in run.ts to specify --version=3.5.1 in PR #1186  for now.

**Comment by sarangan12** [comment]
@qiaozha Could you please confirm if you still have this problem?

**Comment by sarangan12** [comment]
I have tested the latest core and no issue is found. I am resolving this issue

**Comment by qiaozha** [comment]
okay. Thanks
