### ISSUE TITLE
[HLC Track1] The integration cases related to user agents failed due to tough-cookie upgrade

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1516]
After the upgrading tough-cookie of the sub-dependency of core-http our test cases failed. More discussion could be found [here](https://github.com/Azure/azure-sdk-for-js/issues/23004). We'd like to investigate if we still need these cases and if yes we'll lock the version in our project to workaround.

Our test cases failed with below message [link here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1799698&view=logs&j=71cc2e7d-6454-5bf0-71b5-f1eef07a6c23&t=f2857310-5d68-5640-1409-0ba88dcfe076):

```
13) Integration tests for User Agents
       should send correct user agent string with custom string for core v1:
     Error: Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}.
      at Object.getPublicSuffix (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/tough-cookie@4.1.0/node_modules/tough-cookie/lib/pubsuffix-psl.js:62:11)
      at permuteDomain (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/tough-cookie@4.1.0/node_modules/tough-cookie/lib/permuteDomain.js:38:28)
      at MemoryCookieStore.findCookies (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/tough-cookie@4.1.0/node_modules/tough-cookie/lib/memstore.js:99:21)
      at MemoryCookieStore.findCookies (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/universalify@0.2.0/node_modules/universalify/index.js:5:67)
      at CookieJar.getCookies (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/tough-cookie@4.1.0/node_modules/tough-cookie/lib/cookie.js:1407:11)
      at CookieJar.getCookies (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/universalify@0.2.0/node_modules/universalify/index.js:5:67)
      at CookieJar.getCookieString (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/tough-cookie@4.1.0/node_modules/tough-cookie/lib/cookie.js:1452:21)
      at CookieJar.getCookieString (/Users/runner/work/1/s/common/temp/node_modules/.pnpm/universalify@0.2.0/node_modules/universalify/index.js:5:67)
      at /Users/runner/work/1/s/common/temp/node_modules/.pnpm/@azure+core-http@1.2.6/node_modules/@azure/core-http/src/nodeFetchHttpClient.ts:95:25
      
```

**Comment by MaryGao** [comment]
@joheredi Do you think we still need these test cases? According to Jeff's [comment ](https://github.com/Azure/azure-sdk-for-js/issues/23004#issuecomment-1227643372)`, How do you think?

> having support for cookies in core is degenerate

**Comment by joheredi** [comment]
We need to keep supporting cookies, at least on our tests because that's the way test server tracks the scenario. Are all tests using cookies failing?

**Comment by MaryGao** [comment]
Thanks for the update! No currently the test cases passed and relevant issue resolved.

**Comment by MaryGao** [comment]
Issue resolved after upgrading to the latest tough-cookie
