### ISSUE TITLE
[DPG]Code gen failure with OpenAI.Inference June preview rest spec

### ISSUE THREAD

**Issue by glharper** [Azure/autorest.typescript#1901]
[Link to failing build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2854269&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2)

The error in SDK Automation for azure-sdk-for-js:
10:53:25.949 cmderr 	[automation_generate.sh] Failed to format file: /mnt/vss/_work/1/s/azure-sdk-for-js/sdk/openai/azure-ai-openai/src/rest/models.ts
10:53:25.952 cmderr 	[automation_generate.sh] ExternalError: Emitter "@azure-tools/typespec-ts" failed!
10:53:25.952 cmderr 	[automation_generate.sh] File issue at https://github.com/Azure/autorest.typescript/issues
10:53:25.952 cmderr 	[automation_generate.sh] Error: Cannot find module './parser-typescript.js'
10:53:25.952 cmderr 	[automation_generate.sh] Require stack:
10:53:25.952 cmderr 	[automation_generate.sh] - /mnt/vss/_work/1/s/azure-sdk-for-js/sdk/openai/azure-ai-openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/prettier/index.js
10:53:25.952 cmderr 	[automation_generate.sh]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
10:53:25.952 cmderr 	[automation_generate.sh]     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
10:53:25.953 cmderr 	[automation_generate.sh]     at Module.require (node:internal/modules/cjs/loader:1098:19)
10:53:25.953 cmderr 	[automation_generate.sh]     at require (node:internal/modules/cjs/helpers:108:18)
10:53:25.953 cmderr 	[automation_generate.sh]     at Object.get typescript [as typescript] (/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/openai/azure-ai-openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/prettier/index.js:30369:16)
10:53:25.953 cmderr 	[automation_generate.sh]     at resolveParser (/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/openai/azure-ai-openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/prettier/index.js:7492:25)

[more lines at build link]

**Comment by MaryGao** [comment]
Thanks for reaching out! I will try to identify the root cause and fix it.

**Comment by MaryGao** [comment]
@glharper I did a fix [here](https://github.com/Azure/autorest.typescript/pull/1904) so that we could generate the OpenAI SDK without errors in our smoke testing environment.
Back to the ci errors when generating openai, I assume there still exists some extra effort in our automation tools and notice @deyaaeldeen was working on that but he is on vacation recently. So I'd like to confirm with you if the ci error fix is urgent or if we have any release plan for openai SDK?
