### ISSUE TITLE
RangeError: Maximum call stack size exceeded at getResponseMapping

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#1982]
Full error:

> ExternalError: Emitter "@azure-tools/typespec-ts" failed!
File issue at https://github.com/Azure/autorest.typescript/issues

> RangeError: Maximum call stack size exceeded
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:400:35)
    at deserializeResponseValue (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:441:59)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:419:53)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:412:179)
    at deserializeResponseValue (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:441:59)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:419:53)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:412:179)
    at deserializeResponseValue (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:441:59)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:419:53)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:412:179)
    at runEmitter (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@typespec/compiler/dist/src/core/program.js:583:19)
    at async compile (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@typespec/compiler/dist/src/core/program.js:257:9)
    at async compileOnce (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:37:25)
    at async compileAction (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:21:9)

## Repro steps:
- edit `sdk/openai/openai/tsp-location.json` and set the commit to `0d3d201639b9e7f3f448bbd08b1fe2fd461ecf49`
- run `rushx generate`

You can find the typespec in https://github.com/Azure/azure-rest-api-specs/pull/25271

This is high priority to unblock the openai release scheduled later this month.

**Comment by qiaozha** [comment]
After investigation, this is because the typespec is defined as circular reference.
```
@doc("A single, role-attributed message within a chat completion interaction.")
model ChatMessage {
  @doc("The role associated with this message payload.")
  @projectedName("json", "role")
  role: ChatRole;

  #suppress "@azure-tools/typespec-azure-core/no-nullable" "we explicitly want a nullable string"
  @doc("The text associated with this message payload.")
  @projectedName("json", "content")
  content: string | null;

  @doc("""
    The name of the author of this message. `name` is required if role is `function`, and it should be the name of the
    function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of
    64 characters.
    """)
  @added(ServiceApiVersions.v2023_07_01_Preview)
  name?: string;

  @doc("The name and arguments of a function that should be called, as generated by the model.")
  @added(ServiceApiVersions.v2023_07_01_Preview)
  @projectedName("json", "function_call")
  functionCall?: FunctionCall;

  @doc("""
    Additional context data associated with a chat message when requesting chat completions using compatible Azure
    OpenAI chat extensions. This includes information like the intermediate data source retrievals used to service a
    request.
    This context information is only populated when using Azure OpenAI with chat extensions capabilities configured.
  """)
  @added(ServiceApiVersions.v2023_08_01_Preview)
  @projectedName("csharp", "AzureExtensionsContext")
  context?: AzureChatExtensionsMessageContext;
}

@added(ServiceApiVersions.v2023_08_01_Preview)
@doc("""
  A representation of the additional context information available when Azure OpenAI chat extensions are involved
  in the generation of a corresponding chat completions response. This context information is only populated when
  using an Azure OpenAI request configured to use a matching extension.
""")
model AzureChatExtensionsMessageContext {
  @doc("""
    The contextual message payload associated with the Azure chat extensions used for a chat completions request.
    These messages describe the data source retrievals, plugin invocations, and other intermediate steps taken in the
    course of generating a chat completions response that was augmented by capabilities from Azure OpenAI chat
    extensions.
  """)
  messages?: ChatMessage[];
}
```
ChatMessage has a property context with the type of a model AzureChatExtensionsMessageContext which has a property messages with the type of an array of ChatMessage.  

As this circular references is not very easy to detect if there's multiple layers in this circular, and current code implementation doesn't record which type is currently being deserialized. 

We use hard code for messages/message to cast it as any to work around the ocmpile in PR https://github.com/Azure/autorest.typescript/pull/1986/files#r1299670689 

we will need to add a manual deserialize function 

```typescript
function deserializeMessage(message: ChatMessageInRest): ChatMessage {
  return {
    role: message["role"],
    content: message["content"],
    name: message["name"],
    functionCall: !message.function_call
      ? undefined
      : {
          name: message.function_call?.["name"],
          arguments: message.function_call?.["arguments"],
        },
    context: !message.context
      ? undefined
      : {
          messages: !message.context.messages
            ? undefined
            : message.context.messages.map((m) => {
                return deserializeMessage(m);
              }),
        },
  };
}
```

**Comment by deyaaeldeen** [comment]
@qiaozha Thanks for the quick turnaround! However, just to confirm, is there a plan for a stable fix that takes circular reference into account?

**Comment by qiaozha** [comment]
Yeah, I will get to this when https://github.com/Azure/autorest.typescript/pull/1962 is done, because in this PR, we have codegen logic for special deserialization helper. And circular reference would be considered as one of the case.

**Comment by joheredi** [comment]
I can't reproduce anymore, I was able to generate sucessfully the commit above and also this [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWyXLIG0HEWS5Db3Jl0hIuVHJhaXRzOwoKQHVzZUF1dGgoCiAgQXBpS2V5xA48xgtMb2NhdGlvbi5oZWFkZXIsICJhcGkta2V5Ij4gfCBPxCoyxS9bCiAgICB7xQYgIOQA3DrHH0Zsb3fkAKUuaW1wbGljaXQsxyVhdXRob3JpesVhVXJsOiAi5AFoczovL2xvZ2luLmNvbnRvc28uY29tL2NvbW1vbi9vxDUyL3YyLjAvyEBlIshSc2NvcGVzOiBbyUl3aWRnZXTNSi5kZWZhdWx0Il3GN30KICBdPgopCkBzZXJ2aWNlKOQAxnRpdGxlOiAiQ8Y6IFfFSSBNYW5hZ2VyIiwKfccxZXLkATkie2VuZHBvaW50fcd05QCV0D9BUElzxRnEYyAgQGRvYygiIiIKU3Vw5AIiZWTIKVPmAItzIMhXcyAocHJvdG9jb2wgYW5kIGhvc3RuYW1lLCBmb3IgZXhhbXBsZToK6QD4ZXN0dXMuYXBpLvIBAykuCiIiIinlAIPIYDogc3RyaW5n5ACdfeQBDecCwWVkKOcAxC7mAJvnAQLoAm9zKQrkAIdzcGFjZSDVKuQCY%2BUA6FRoySLvAU8g5wF6IMd1LiIpCmVudW0gyGXlATDGRscTIDIwMjItMDgtMzHlAMrkAsZEZXBlbmRlbmN5KOsC6chELnYxXzBfUHJldmlld18yxDVgyUUwYCwKfQoKYWxpYXMgQ2hhdFJvbGUgPSAiYWRtaW4iIHwgInVzZXLkA6HmAIdBIOQDUWxlLCByb2xlLWF0dHJpYnXkAcJtZXNzYWdlIHdpdGhpbiBhIGNoYXQgY2%2FkAaHkAuogaW50ZXJhY8QM5ADpbW9kZWzFdE3HOuQA7SNzdXBwcmVzc%2F8ENm9yZS9uby1udWxsYWJsZSIgIndlIGV45gNqbHkgd2FudCBhIMgg5wHmIukBT%2BQBlXRleHQgYXNzb2NpYeQAwuQAuiB0aGlz6QDMcGF5bG9hZOQAryAgQHByb2plY3RlZE5hbWUoImpzb24iLCAi5AJiZW50xSTHDOgCViB85QCCOwrJeCLkAIMgIMR%2F5AJAIG9mIHRoZecEFMYO6gCALiBgxCVgIGlzIHJlcXVpcmVkIGlm5QF7xBRgZnVu5QFQYCzlAx1pdCBzaG91bGQgYmXFV8tjxXfIMCB3aG9zZSByZXNwb25zxUxpbsUyYOcAwmAuIE1heeUA0GHkAc4teiwgQS1aLCAwLTnGbXVuZGVyc%2BQBiXMs5gE7YSBtYXhpbXVtIGxlbmd0aCBvZsV2NjTkAgzkAftlcnMuxRPnA4jkAKA%2F6AEt8gEmQWRkaeQAr2Fs5gFZeHQgZGF0YfEBtOcCbOkCgmhlbuUBMGVzdOQBhe8CiXMg5gYVxBJhdGnkAh7lAzfFc09wZW5BScYzZXh0ZW7mA0QgVOQBl2luY2x1ZGXECWZvcm3lBcEgbGlr5gFt5QLgbWVk5ACZ5gCoc291cmPkAWd0cmlldmFsxHplZCB0b%2BkD%2BWHFdecArOYBG8Vq6ADvzGlpcyBvbmx5IHBvcHVs5gD95ADp6wbi6AC%2B5QEV7wDDIGNhcGFiaWxpdGllxWBmaWd1cmVkxHXnAY7wAuFjc2hhcnDkAuPFXkXJTOQEzmV46wLyeHQ%2FOuYAg%2BQD0Mop5wPaxzA75ARr6wHhQSByZeQD7GVudOYA4ugDDfIB9%2BwBCGF2YWnmA9XlAQDtAPrwAPVhcuQBmHZvbHZlZAog6ALlZ2VuZXLJc2EgY29y5gMLZPUCL8Ycc2XnAgb%2FAZzrAZwKIOcBnmHvAKfnAfHrAYfkAhV1c2XlA0R0Y2jENekAx%2BcGt%2BYFMf8BZnh06wY06wRt5wC1dWFs8ATd8wUC5wMR8QFO5QK%2B5Ad48QXd5gSg6wLEZXNlyGlzIGRlc2NyaecElPYDGiwgcGx1Z2nkBiZ25wl8c%2BYEaG90aGVy7gNdc3RlcHMgdGFrZcQw6QTeY291cnPlBPDoAeHkAXv6AdAgdMQad2FzIGF1Z21lbuQBAmJ57gMpZnJvbfICY8Vv6wQf6gNE6AD0PzrsBttbXeUC%2FOUAxWblCDLEeuYJDW9wIGNyZeQA12lz7AqpUnBjT3DnAqc8e30szFA%2BCn0%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D) which contains @qiaozha models above.

Feel free to re-open if you can get a repro

**Comment by deyaaeldeen** [comment]
@joheredi I think you can't repro it because it has been addressed in a hacky way temporarily but it still needs to be addressed in a more principled way. @qiaozha Could you please share an update on progress towards fixing this?

**Comment by minhanh-phan** [comment]
I currently run into this issue and it is blocking the generation for the latest features. To reproduce, use the latest commit id from [this PR](https://github.com/Azure/azure-rest-api-specs/pull/26737), currently I'm using `c8be3dc86f4dcfd3a2bd4f8a56233ff6212e679e` with 0.19.0 version of the emitter. I'll run into the same error. 

```
Emitter "@azure-tools/typespec-ts" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.typescript/issues

RangeError: Maximum call stack size exceeded
    at deserializeResponseValue (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:519:34)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:508:57)
    at deserializeResponseValue (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:537:48)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:508:57)
    at getResponseMapping (file:///home/codespace/workspace/sdk/openai/openai/TempTypeSpecFiles/OpenAI.Inference/node_modules/@azure-tools/typespec-ts/dist/src/modular/helpers/operationHelpers.js:492:179)
```

**Comment by minhanh-phan** [comment]
The circular dependency is similar to what @qiaozha commented above. It's `ChatResponseMessage` defined [here](https://github.com/Azure/azure-rest-api-specs/blob/c8be3dc86f4dcfd3a2bd4f8a56233ff6212e679e/specification/cognitiveservices/OpenAI.Inference/models/completions/chat_messages.tsp#L204C1-L210C2) and `AzureChatExtensionsMessageContext` defined [here](https://github.com/Azure/azure-rest-api-specs/blob/c8be3dc86f4dcfd3a2bd4f8a56233ff6212e679e/specification/cognitiveservices/OpenAI.Inference/models/completions/azure_chat_extensions.tsp#L84C1-L93C1) that create the circular dependency.

**Comment by qiaozha** [comment]
Pending on a new release of the emitter.
