### ISSUE TITLE
Form data policy is not working in browser environment

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2179]
In https://github.com/Azure/autorest.typescript/pull/2174, we found this issue when upgrading core-rest-pipeline to the latest. Which the browser testing failed with below errors:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=3364401&view=logs&j=ab43a7c6-591e-5343-e40e-ecefe341dfcc&t=f5a3af97-b9f3-594b-1a83-577f98fc3b13&l=860
```
Chrome Headless 83.0.4103.0 (Linux x86_64) Integration tests for BodyFormData should correctly accept file via form FAILED
	RestError: Error sending request: Failed to fetch
	    at getError (test-browser/webpack:/common/temp/node_modules/.pnpm/@azure+core-rest-pipeline@1.13.0/node_modules/@azure/core-rest-pipeline/src/fetchHttpClient.ts:191:12)
	    at FetchHttpClient.sendRequest (test-browser/webpack:/common/temp/node_modules/.pnpm/@azure+core-rest-pipeline@1.13.0/node_modules/@azure/core-rest-pipeline/src/fetchHttpClient.ts:48:13)
	    at Object.sendRequest (test-browser/webpack:/common/temp/node_modules/.pnpm/@azure+core-rest-pipeline@1.13.0/node_modules/@azure/core-rest-pipeline/src/policies/retryPolicy.ts:58:22)
	    at sendRequestAsStream (test-browser/webpack:/common/temp/node_modules/.pnpm/@azure-rest+core-client@1.1.6/node_modules/@azure-rest/core-client/src/sendRequest.ts:81:20)
Chrome Headless 83.0.4103.0 (Linux x86_64): Executed 804 of 1120 (1 FAILED) (skipped 21) (0 secs / 5.69 secs)

```

I notice Timo has a pr which may fix this https://github.com/Azure/azure-sdk-for-js/pull/28103.

**Comment by timovv** [comment]
@MaryGao this is good to close now, right? We managed to validate that the Core PR fixed the issue I think?

**Comment by MaryGao** [comment]
Close this as the browser env issue is fixed.
