### ISSUE TITLE
Generation failure involving JsonProperty and JsonConstructor

### ISSUE THREAD

**Issue by felpel** [Azure/autorest.typescript#235]
## Issue

I've tried to generate the client code for the first time for a new service and I was prompted with this error:
<details>
<summary>Autorest stacktrace</summary>

```bash
AutoRest code generation utility [version: 2.0.4283; node: v8.11.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283\autorest-core -> C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\app.js
C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283\autorest-language-service -> C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\language-service\language-service.js
   Loading AutoRest core      'C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (2.0.367->2.0.367)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
FATAL: System.InvalidOperationException: Property 'agent' in Model 'FpsModel' is marked readOnly and is also required. This is not allowed.
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SchemaBuilder.cs:line 113
   at AutoRest.Modeler.ObjectBuilder.BuildServiceType(String serviceTypeName) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\ObjectBuilder.cs:line 151
   at AutoRest.Modeler.SchemaBuilder.ParentBuildServiceType(String serviceTypeName) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SchemaBuilder.cs:line 209
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SchemaBuilder.cs:line 40
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SchemaBuilder.cs:line 135
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SwaggerModeler.cs:line 300
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\SwaggerModeler.cs:line 69
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISH948lr\22_20171019T215822\autorest.modeler\src\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: typescript/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Process() cancelled due to exception : Plugin modeler reported failure.
  Error: Plugin modeler reported failure.
```
</summary>
</details>

My colleague modeled the following abstraction in C#:

```csharp
[JsonObject(MemberSerialization.OptIn)]
public sealed class AgentModel
{
        #region Properties
     
        [JsonProperty(PropertyName = "agentId", Required = Required.Always)]
        public string AgentId { get; }

        // Other properties omitted

       #endregion

        #region Constructors

        [JsonConstructor]
        public AgentModel(string agentId)
        {
            AgentId = agentId;
            // Other constructor parameters omitted
        }

        #endregion
}
```

He was able to generate the C# client code successfully with Autorest, but we didn't succeed for the TS one. In this context, the error shouldn't occur since we define a `JsonConstructor` that will handle the read-only property (`AgentId`). As a workaround, we could remove the `Required` property in the `JsonProperty` attribute, but we would like to keep it that way, but we might be wrong. If the issue is not related specifically to the TS extension, let me know and I will export the issue in the appropriate repository.

### Service's configuration

```yaml
typescript: true
use:
  - "@microsoft.azure/autorest.typescript@2.0.367"
input-file:
  - (external swagger.json)
add-credentials: true
verbose: true
output-folder: './../gateway'
```

### `autorest --info`

```bash
AutoRest code generation utility [version: 2.0.4283; node: v8.11.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions
 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4280     C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4280
 core       @microsoft.azure/autorest-core           2.0.4283     C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4283
 extension  @microsoft.azure/autorest.modeler        2.1.23       C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.modeler@2.1.23
 extension  @microsoft.azure/autorest.typescript     2.0.304      C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.typescript@2.0.304
 extension  @microsoft.azure/autorest.typescript     2.0.330      C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.typescript@2.0.330
 extension  @microsoft.azure/autorest.typescript     2.0.367      C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.typescript@2.0.367
```

**Comment by RikkiGibson** [comment]
The problem seems related to conflating the language concept of "read-only property" with the Swagger concept of "read-only property".

In Swagger, read-only means that a property shouldn't be sent by the server--i.e. only values received from the server for that property are allowed. In C# and TS, the user can specify any value for that property, they just can't change it after creation.

Could you share a snippet of the Swagger generated from the `AgentModel`? Is this using Swashbuckle?

**Comment by felpel** [comment]
@RikkiGibson : yes, we use Swashbuckle.

Here's the generated JSON (other properties omitted):

![image](https://user-images.githubusercontent.com/5000004/43859679-58f5f3d2-9b1f-11e8-8da5-54fd2a5dc246.png)

**Comment by RikkiGibson** [comment]
I tried creating a similar model in [Swagger Editor](https://editor.swagger.io) and found this error:
<img width="1047" alt="screen shot 2018-08-08 at 12 30 44 pm" src="https://user-images.githubusercontent.com/5833655/43859931-f384c46e-9b06-11e8-9f2a-b46a0386f040.png">

@fearthecowboy was there a recent change made to the modeler to support models like the one above for C#?

Is Swashbuckle is using the lack of a setter on the property to mean "readOnly" in Swagger? That feels like a mistake on their side.

**Comment by fearthecowboy** [comment]
Not that I'm aware of.

`readOnly` and `required` can  not be specified together.  

It's possible in c# it's letting it thru.

**Comment by felpel** [comment]
From what I understand, maybe the problem would be located in `Swashbuckle`'s logic? 

I could open an issue on their repository and see if they can do something about this. 

Note that I don't see the error badge when I navigate to the Swagger UI endpoint, even though multiple errors are flagged in the online Swagger editor.

**Comment by RikkiGibson** [comment]
Thanks for bringing the issue to our attention @felpel--please reopen if there's anything actionable on the autorest.typescript for this.
