### ISSUE TITLE
Crash for TS DPG

### ISSUE THREAD

**Issue by glharper** [Azure/autorest.typescript#2554]
Genning from [AI Inference Typespec](https://github.com/Azure/azure-rest-api-specs/commit/d4cb3a1cfa9ec74e75fed7240aab03ddd777414b) into TypeScript

Error: Did you mean to provide the overwrite option? A source file already exists at the provided file path: C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/src/utils/serializeUtil.ts
    at CompilerFactory.throwIfFileExists (C:\Users\glharper\repos\azure-sdk-for-js\sdk\ai\TempTypeSpecFiles\ModelClient\node_modules\ts-morph\dist\ts-morph.js:19200:15)
    at CompilerFactory.createSourceFileFromText (C:\Users\glharper\repos\azure-sdk-for-js\sdk\ai\TempTypeSpecFiles\ModelClient\node_modules\ts-morph\dist\ts-morph.js:19193:14)
    at CompilerFactory.createSourceFile (C:\Users\glharper\repos\azure-sdk-for-js\sdk\ai\TempTypeSpecFiles\ModelClient\node_modules\ts-morph\dist\ts-morph.js:19181:25)
    at Project.createSourceFile (C:\Users\glharper\repos\azure-sdk-for-js\sdk\ai\TempTypeSpecFiles\ModelClient\node_modules\ts-morph\dist\ts-morph.js:20163:46)
    at buildSerializeUtils (file:///C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/TempTypeSpecFiles/ModelClient/node_modules/@azure-tools/typespec-ts/dist/src/modular/buildSerializeUtils.js:18:41)
    at generateModularSources (file:///C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/TempTypeSpecFiles/ModelClient/node_modules/@azure-tools/typespec-ts/dist/src/index.js:121:17)
    at Object.$onEmit [as emitFunction] (file:///C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/TempTypeSpecFiles/ModelClient/node_modules/@azure-tools/typespec-ts/dist/src/index.js:43:11)
    at async runEmitter (file:///C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/TempTypeSpecFiles/ModelClient/node_modules/@typespec/compiler/dist/src/core/program.js:555:13)
    at async compile (file:///C:/Users/glharper/repos/azure-sdk-for-js/sdk/ai/TempTypeSpecFiles/ModelClient/node_modules/@typespec/compiler/dist/src/core/program.js:237:9)
    at async compileTsp (file:///C:/Users/glharper/AppData/Roaming/nvm/v18.18.2/node_modules/@azure-tools/typespec-client-generator-cli/dist/typespec.js:76:21)

--------------------------------------------------
Library Version                0.29.0
TypeSpec Compiler Version      0.56.0
--------------------------------------------------

**Comment by glharper** [comment]
The issue here is multiple client definitions, causing the typespec-ts emitter to throw.

**Comment by kazrael2119** [comment]
close as this issue should be resolved
