### ISSUE TITLE
Unable to generate SDK from the 3rd party sample in https://www.speakeasy.com/openapi/frameworks/typespec

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#2968]
Repo:

1. Follow the steps in https://www.speakeasy.com/openapi/frameworks/typespec to create the project.
2. Use the main.tsp defined in the above page.
3. Update the tspconfig.yaml as below:

```
emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    isModularLibrary: true
    azureSdkForJs: false
    emitter-output-dir: "{project-root}/../clients/javascript"
```

Then run `tsp install`  & `tsp compile .`

Expected:  Generate the JS modular SDK without problem.

Actual:  CodeGen crashed with the following error:

TypeSpec compiler v0.63.0

Emitter "@azure-tools/typespec-ts" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.typescript/issues

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getNameAndPropertyMap (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:113:39)
    at transformIsDefaultSupersetOfOthers (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:98:60)
    at transformToResponseTypesForRoute (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:74:13)
    at transformToResponseTypes (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:31:13)
    at transformRLCModel (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/transform/transform.js:31:23)
    at buildRLCCodeModels (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/index.js:134:37)
    at Object.$onEmit [as emitFunction] (file:///D:/work/typespec-example-speakeasy/node_modules/@azure-tools/typespec-ts/dist/src/index.js:82:11)
    at async runEmitter (file:///D:/work/typespec-example-speakeasy/node_modules/@typespec/compiler/dist/src/core/program.js:366:13)
    at async compile (file:///D:/work/typespec-example-speakeasy/node_modules/@typespec/compiler/dist/src/core/program.js:123:9)

**Comment by aelij** [comment]
I think the following function is missing an `if (schema.properties)` (instead of using `properties!`...). In my case, this happens when an operation's return type is a union, which indeed doesn't have properties.

https://github.com/Azure/autorest.typescript/blob/c5d27046e119854ad7f6d11ffbd94b6d87e097c7/packages/typespec-ts/src/transform/transformResponses.ts#L170-L175

**Comment by qiaozha** [comment]
@aelij thank you very much for your suggestion, your fix is indeed a solution. However, per our internal discussion, this logic is outdated as we don't need to generate rest level client code inside our modular. Here is my fix to this https://github.com/Azure/autorest.typescript/pull/3057 

Feel free to let me know if you have any concerns.
