### ISSUE TITLE
Generation failure with some conditions

### ISSUE THREAD

**Issue by grhbit** [Azure/autorest.typescript#408]
Generation failed if operationId contains period and any parameters set required field to false.

Related to #382.

OS: OS X 10.14.1 (18B75)
node: v11.3.0

## Configuration

```yaml
# specify the version of Autorest to use
version: latest

input-file: sample.yaml

output-folder: dist-autorest

use-extension:
  "@microsoft.azure/autorest.typescript": "2.1.2"
  "@microsoft.azure/autorest.modeler": "2.3.51"
```

fails
```yaml
swagger: '2.0'
tags:
  - name: bug
    description: Exception occured!
schemes:
  - http
definitions:
  Tag:
    title: Tag
    description: Tagging
    type: object
    properties:
      name:
        type: string
info:
  title: sample
  version: v0.0.1
paths:
  /:
    get:
      tags:
        - bug
      description: autorest is great!
      operationId: getStatus.fail
      parameters:
        - in: query
          name: name
          required: false
          type: string
      responses:
        204:
          description: No content
```

success case 1 (Generation succeed but code has compilation error)
```yaml
swagger: '2.0'
tags:
  - name: bug
    description: Exception occured!
schemes:
  - http
definitions:
  Tag:
    title: Tag
    description: Tagging
    type: object
    properties:
      name:
        type: string
info:
  title: sample
  version: v0.0.1
paths:
  /:
    get:
      tags:
        - bug
      description: autorest is great!
      operationId: getIndex.notFailsButWrongCodeGeneration
      parameters:
        - in: query
          name: name
          required: true
          type: string
      responses:
        204:
          description: No content
```

success case 2 (It works!)
```yaml
swagger: '2.0'
tags:
  - name: bug
    description: Exception occured!
schemes:
  - http
definitions:
  Tag:
    title: Tag
    description: Tagging
    type: object
    properties:
      name:
        type: string
info:
  title: sample
  version: v0.0.1
paths:
  /:
    get:
      tags:
        - bug
      description: autorest is great!
      operationId: getIndex
      parameters:
        - in: query
          name: name
          required: false
          type: string
      responses:
        204:
          description: No content
```

failed log (with debug option)
```sh
# ... (Skipped)
DEBUG: typescript/cm/emitter - END
INFORMATION: The output folder doesn't contain a pre-existing package.json file to get the package version from.
DEBUG: [WRITING] ServiceClientTemplate => lib/sample.ts
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.TypeScript.Model.MethodTS.get_OptionsParameterModelType() in /home/vsts/work/1/s/src/vanilla/Model/MethodTS.cs:line 134
   at AutoRest.TypeScript.Model.MethodTS.GetOptionsParameter(Boolean required) in /home/vsts/work/1/s/src/vanilla/Model/MethodTS.cs:line 742
   at AutoRest.TypeScript.Model.MethodTS.Generate(TSClass tsClass) in /home/vsts/work/1/s/src/vanilla/Model/MethodTS.cs:line 763
   at AutoRest.TypeScript.CodeGeneratorTS.GenerateMethods(IEnumerable`1 methods, String emptyLine) in /home/vsts/work/1/s/src/vanilla/CodeGeneratorTS.cs:line 266
   at AutoRest.TypeScript.vanilla.Templates.ServiceClientTemplate.<ExecuteAsync>d__1.MoveNext() in /home/vsts/work/1/s/src/obj/Razor/vanilla/Templates/ServiceClientTemplate.cshtml:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in /home/vsts/work/1/s/autorest.common/src/CodeGenerator.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.TypeScript.CodeGeneratorTS.<Generate>d__6`1.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorTS.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.TypeScript.CodeGeneratorTS.<Generate>d__5.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorTS.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.TypeScript.Program.<ProcessInternal>d__4.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: typescript/generate - FAILED
FATAL: Error: Plugin typescript reported failure.
Process() cancelled due to exception : Plugin typescript reported failure.
  Error: Plugin typescript reported failure.
```

**Comment by joheredi** [comment]
This should be fixed in the v6
