### ISSUE TITLE
Error: Plugin typescript reported failure.

### ISSUE THREAD

**Issue by cheahengteong** [Azure/autorest.typescript#826]
**Describe the bug**
I had try the v2/1a-code-generation-minimal and it show me **Error: Plugin typescript reported failure.**
```
cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ autorest --typescript --output-foler=Samples\openapi-v2\1a-code-generation-minimal\output --input-file=Samples/openapi-v2/1a-code-generation-minimal/petstore.json --packagename=petstore --package-version=2.0
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\cheahengsoon\.autorest\@autorest_core@3.0.6349\node_modules\@autorest\core\dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/SchemaMissingType): The schema 'User' with an undefined type and decalared properties is a bit ambigious. This has been 
auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Category' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Pet' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Order' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: Error: Unexpected value type: Sequence
    at Object.getStringForValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\utils\valueHelpers.js:60:19)
    at writeDefaultValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:220:61)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:107:9
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
    at CodeBlockWriter.inlineBlock (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:141:14)
    at CodeBlockWriter.block (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:130:14)
    at Object.writeMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:104:12)
    at writeParameterMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:76:28)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:52:17
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
FATAL: Error: Unexpected value type: Sequence
  Error: Plugin typescript reported failure.

cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 102 packages in 1.473s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ autorest --typescript --output-foler=Samples\openapi-v2\1a-code-generation-minimal\output --input-file=Samples/openapi-v2/1a-code-generation-minimal/petstore.json --packagename=petstore --package-version=2.0
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\cheahengsoon\.autorest\@autorest_core@3.0.6349\node_modules\@autorest\core\dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/SchemaMissingType): The schema 'User' with an undefined type and decalared properties is a bit ambigious. This has been 
auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Category' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Pet' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Order' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: Error: Unexpected value type: Sequence
    at Object.getStringForValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\utils\valueHelpers.js:60:19)
    at writeDefaultValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:220:61)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:107:9
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
    at CodeBlockWriter.inlineBlock (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:141:14)
    at CodeBlockWriter.block (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:130:14)
    at Object.writeMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:104:12)
    at writeParameterMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:76:28)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:52:17
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
FATAL: Error: Unexpected value type: Sequence
  Error: Plugin typescript reported failure.
```

**Comment by sarangan12** [comment]
@cheahengteong Thanks for reporting this issue. I have checked it. With the latest V6 Generator, I do get the same error as you reported. 

**Where is the error happening?**

The error happens in the following JSON snippet:

```json
"/pet/findByStatus": {
    "get": {
        ..........
        ..........
        "parameters": [{
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "csv",
            "default": "available"
    }],
    ......
    ......
}
```

**What is the error?**
In the above snippet, you can see that the ```"type": "array"```. This is translated by Autorest Core to ```MapperType.Sequence```. This ```MapperType.Sequence``` is not handled in the V6 Code Generator. Thus this results in the error (reported above in the issue description).

**What happens in the old generator?**
In the old generator, the SDK generation does not crash with error. But, the generated code is incorrect. The following code is generated by the SDK:

```js
export const status: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "status"
  ],
  mapper: {
    serializedName: "status",
    defaultValue: available, //<----- This is not correct. available is a string. It is generated as a variable which will error in build
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: msRest.QueryCollectionFormat.Csv
};
```

**Next Steps**
The ```MapperType.Sequence``` must be handled correctly in the V6 Code Generator. I will create the PR Soon.

**Comment by sarangan12** [comment]
With the fix in PR https://github.com/Azure/autorest.typescript/pull/843, this issue has been fixed. I have tested with the petstore.json and it is working fine with versiob v6.0.0-dev.20210121.2.(https://github.com/Azure/autorest.typescript/releases) Closing the issue. 

If you still face any issues, feel free to reopen the issue.
