### ISSUE TITLE
Referencing an empty definition via allOf breaks client generation

### ISSUE THREAD

**Issue by forteddyt** [Azure/autorest.typescript#848]
**Describe the issue or request**
Scenarios such as the following (Note the **"allOf"**):
```json
"definitions":{
    "LongRunningNullResponse": {
      "type": "object",
      "additionalProperties": false
    },
    "LongRunningNullResponseLongRunningOperationResponse": {
      "type": "object",
      "properties": {
        "completionResult": {
          "allOf": [
            {
              "$ref": "#/definitions/LongRunningNullResponse"
            }
          ]
        },
        "location": {
          "format": "uri",
          "type": "string"
        }
      },
      "additionalProperties": false
    }
}
```
break client generation with the following error
```
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 142
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in c:\publish\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: typescript/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
```

A pipeline failure example: https://github.com/Azure/azure-rest-api-specs/pull/12554/checks?check_run_id=1752851769. This is also an issue with the Python and C# client generations and I have filed issues in their respective repos. [Python Issue](https://github.com/Azure/autorest.python/issues/871), [C# Issue](https://github.com/Azure/autorest.csharp/issues/997).

**Describe your ideas for solutions**
The solution is relatively straight forward for my scenario. Removing the allOf wrapper around the reference resolves the issue.
```json
"definitions":{
    "LongRunningNullResponse": {
      "type": "object",
      "additionalProperties": false
    },
    "LongRunningNullResponseLongRunningOperationResponse": {
      "type": "object",
      "properties": {
        "completionResult": {
          "$ref": "#/definitions/LongRunningNullResponse"
        },
        "location": {
          "format": "uri",
          "type": "string"
        }
      },
      "additionalProperties": false
    }
}
```

**Comment by sarangan12** [comment]
As discussed in the csharp issue, you could simplify the swagger and remove the allof operator. I would definitely recommend you to modify the swagger. 

On the other hand, with the latest [JS SDK generator](https://www.npmjs.com/package/@autorest/typescript) this issue has been resolved. I have checked the given swagger and it generated the following code:

```js
export interface LongRunningNullResponseLongRunningOperationResponse {
  completionResult?: LongRunningNullResponseLongRunningOperationResponseCompletionResult;
  location?: string;
}

export interface LongRunningNullResponseLongRunningOperationResponseCompletionResult {}
```

Please let me know if you have any more questions.
